### PR TITLE
Added wiki, updated links

### PR DESCRIPTION
**Pull request by stefonarch**
schermata-07-18-14-49

Not sure about the "development".

### CODE REVIEW

**Comment by tsujan** [comment]
> Not sure about the "development".

It's good.

**Comment by stefonarch** [comment]
The "team link" in the second tab (and maybe not only that) could be changed too, pointing to "people":
https://github.com/orgs/lxqt/people

**Comment by stefonarch** [comment]
Changed also the links in the 2+"authors" tab to 
https://github.com/lxqt/
https://github.com/orgs/lxqt/people

**Comment by tsujan** [comment]
I think it's good to merge.

**Pull request merged**
