### PR TITLE
update_website_link

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
Not sure about copyright: LXQt Team or LXQt Project?

**Comment by tsujan** [comment]
I don't think it's important but the project seems better; the team may change.

**Comment by stefonarch** [comment]
Changed to "Project" everwhere.
I think there are tons of links to lxqt.org  in the source files around.

**Comment by tsujan** [comment]
> I think there are tons of links to lxqt.org in the source files around

If so, changing all of them will be very difficult if not torturous. What about leaving them as remnants of old times and add a single explanation somewhere?

**Comment by stefonarch** [comment]
Just replace the link requires only one `find ./ exec sed` command, copyright info is harder.

**Pull request merged**
