### PR TITLE
Sort translators by language name

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by tsujan** [comment]
@palinek 
Would you check if there's a shorter method?

**Review by stefonarch — APPROVED** [review]
Works as expected.

**Comment by palinek** [comment]
Instead of copying & post-processing I would rather directly construct the info correctly ordered:
```diff
diff --git a/translatorsinfo/translatorsinfo.cpp b/translatorsinfo/translatorsinfo.cpp
index e77d584..d4a9ec8 100644
--- a/translatorsinfo/translatorsinfo.cpp
+++ b/translatorsinfo/translatorsinfo.cpp
@@ -359,9 +359,10 @@ TranslatorsInfo::TranslatorsInfo()
     const auto groups = src.childGroups();
     for(const QString& group : qAsConst(groups))
     {
-        QString lang = group.section(QStringLiteral("_"), 1).remove(QStringLiteral(".info"));
+        QString lang = languageToString(group.section(QStringLiteral("_"), 1).remove(QStringLiteral(".info")));
         src.beginGroup(group);
         int cnt = src.allKeys().count();
+        std::set<TranslatorPerson> translators;
         for (int i=0; i<cnt; i++)
         {
             QString nameEnglish = getValue(src, QStringLiteral("translator_%1_nameEnglish").arg(i));
@@ -370,11 +371,12 @@ TranslatorsInfo::TranslatorsInfo()
 
             if (!nameEnglish.isEmpty())
             {
-                process(lang, nameEnglish, nameNative, contact);
+                translators.emplace(std::move(nameEnglish), std::move(nameNative), std::move(contact));
             }
-
         }
         src.endGroup();
+        if (!translators.empty())
+            mLangTranslators.emplace(std::move(lang), std::move(translators));
     }
 }
 
@@ -387,7 +389,7 @@ QString TranslatorsInfo::asHtml() const
         const auto& lang = entry.first;
         const auto& translators = entry.second;
 
-        ret += QLatin1String("<dt><strong>") + languageToString(lang) + QLatin1String("</strong></dt>");
+        ret += QLatin1String("<dt><strong>") + lang + QLatin1String("</strong></dt>");
         for(const auto & translator : translators) {
             ret += QLatin1String("<dd>") + translator.asHtml() + QLatin1String("</dd>");
         }
@@ -397,12 +399,6 @@ QString TranslatorsInfo::asHtml() const
     return ret;
 }
 
-
-void TranslatorsInfo::process(const QString &lang, const QString &englishName, const QString &nativeName, const QString &contact)
-{
-    mLangTranslators[lang].emplace(englishName, nativeName, contact);
-}
-
 QString TranslatorPerson::asHtml() const
 {
     QString ret;
diff --git a/translatorsinfo/translatorsinfo.h b/translatorsinfo/translatorsinfo.h
index 36e9a64..e0a02d9 100644
--- a/translatorsinfo/translatorsinfo.h
+++ b/translatorsinfo/translatorsinfo.h
@@ -73,8 +73,13 @@ public:
     QString asHtml() const;
 
 private:
-    std::map<QString, std::set<TranslatorPerson> > mLangTranslators; //< maps a language to set of it's translators
-    void process(const QString &lang, const QString &englishName, const QString &nativeName, const QString &contact);
+    struct StringLocaleLower {
+        inline bool operator ()(const QString & s1, const QString & s2) const
+        {
+            return QString::localeAwareCompare(s1, s2) < 0;
+        }
+    };
+    std::map<QString, std::set<TranslatorPerson>, StringLocaleLower > mLangTranslators; //< maps a language to set of it's translators
 };
 
 //} //namecpace LXQt
```

**Comment by tsujan** [comment]
@palinek 
Yes, that seems better. Please make a superseding PR.

**Comment by palinek** [comment]
> Please make a superseding PR.

Done in #240

**Comment by tsujan** [comment]
> Done in #240

Thanks!

Superseded by https://github.com/lxqt/lxqt-about/pull/240, which is more frugal.

**Pull request closed without merging**
