### PR TITLE
Using helix icon

### LINKED ISSUE #128: LXQt-About should haver their own icon in .desktop
Instead  of Icon=help-about LXQt could user their own helix as icon.

### PR DESCRIPTION
**Pull request by ecsuarez**
Use the LXQt logo in lxqt-about app. Now lxqt-about provides an own icon, instead of using help-about or an icon of lxqt-themes

Close #128

### CODE REVIEW

**Comment by tsujan** [comment]
I agree that it's better to use LXQt logo here. But the icon "lxqt" belongs to `lxqt-themes`. Maybe, we should add a better SVG file specifically for lxqt-about, like,

lxqt

The original file is this (the bird is quite visible in small sizes too):

[lxqt.svg.zip](https://github.com/lxqt/lxqt-about/files/7545404/lxqt.svg.zip)

**Comment by ecsuarez** [comment]
It's good idea, so lxqt-about should install an lxqt-about icon

**Comment by tsujan** [comment]
> so lxqt-about should install an lxqt-about icon

Yes. Or, perhaps, we could rename it to "lxqt-logo.svg".

**Comment by tsujan** [comment]
@stefonarch and everyone:

Do you prefer `lxqt-about` or `lxqt-logo`?

**Comment by stefonarch** [comment]
> Do you prefer `lxqt-about` or `lxqt-logo`?
`
lxqt-logo` could be used also elsewhere, is more flexible. But I'm fine with both.

**Review by tsujan — APPROVED** [review]
> But I'm fine with both.

Me too.

**Comment by ecsuarez** [comment]
I think that is better lxqt-about, because if some app needed the icon, for example , in a section of a menu, they can use lxqt-about to show the about lxqt as in KDE or other desks.

**Comment by tsujan** [comment]
> i think that lxqt-about can be a link to lxqt-logo, then the two could coexist

Yes, that's also possible.

Anyway, the PR is good. Thanks!

**Comment by ecsuarez** [comment]
Anything  for LXQt!

**Pull request merged**
